services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    profiles:
      - general
      - dev
      - test
    volumes:
      - ./backend/photosite-application/.env:/app/.env:ro
      # Добавил, чтобы статика не копировалась в образ, но лежала на сервере и была доступна в приложении
      - ./backend/photosite-application/static/:/app/static/
    ports:
      - "9000:8000"
    depends_on:
      - pg
      - redis
    
  pg:
    image: postgres:17-alpine
    profiles:
      - general
      - database
      - dev
      - test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Убрать перед сборкой
    # ports:
      # - '5500:5432'
    volumes:
      - photosite_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    profiles:
      - database
      - dev
      - test
    ports:
      - '8080:8080'
    depends_on:
      - pg

  redis:
    image: "redis:alpine"
    # ports:
      # - "6379:6379"
    # volumes:
    #   - redis-data:/data
    # command: redis-server --appendonly yes
    

volumes:
  photosite_data:
  redis-data:
