services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    profiles:
      - general
      - dev
      - test
    volumes:
      - ./backend/photosite-application:/app
    ports:
      - "9000:8000"
    depends_on:
      - pg
    
  pg:
    image: postgres:17-alpine
    profiles:
      - general
      - database
      - dev
      - test
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Убрать перед сборкой
    ports:
      - '5500:5432'
    volumes:
      - photosite_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    profiles:
      - database
      - dev
      - test
    ports:
      - '8080:8080'
    depends_on:
      - pg

volumes:
  photosite_data:
