[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend for photographer's personal site"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.4",
    "pydantic-settings>=2.12.0",
    "pydantic[email]>=2.12.5",
    "uvicorn[standard]>=0.38.0",
]
